modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory

license="MIT License. See in project on github in license file."

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="adjustingbase" #mandatory

version="1.16.3-1.0.0" #mandatory

displayName="Ajusting Base" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/FelipeAlafy/Adjusting-Base" #optional

logoFile="examplemod.png" #optional

credits="Thanks for community of Adjusting Mods!" #optional

authors="Felipe Alafy" #optional

description='''
This mod adds, a news items in game.
'''
[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[34,)" #mandatory

    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
